#!/bin/bash

# Validation script for Chapter 3 URDF code examples
# This script provides instructions for validating the URDF examples

echo "Chapter 3 URDF Code Examples Validation"
echo "======================================="
echo ""
echo "To validate the Chapter 3 URDF examples, follow these steps:"
echo ""
echo "1. Check URDF syntax:"
echo "   cd docs/chapter-3/code-examples"
echo ""
echo "   For differential drive robot:"
echo "   xmllint --noout differential-drive.urdf"
echo ""
echo "   For 3-DOF robot arm:"
echo "   xmllint --noout robot-arm-3dof.urdf"
echo ""
echo "2. Visualize URDF in RViz (if ROS 2 is installed):"
echo "   # Terminal 1:"
echo "   cd docs/chapter-3/code-examples"
echo "   source /opt/ros/humble/setup.bash"
echo "   ros2 run robot_state_publisher robot_state_publisher --ros-args -p robot_description:='$(cat differential-drive.urdf)'"
echo ""
echo "   # Terminal 2:"
echo "   source /opt/ros/humble/setup.bash"
echo "   ros2 run rviz2 rviz2"
echo "   # In RViz: Add -> By display type -> RobotModel"
echo ""
echo "3. Check URDF with check_urdf tool:"
echo "   cd docs/chapter-3/code-examples"
echo "   source /opt/ros/humble/setup.bash"
echo "   check_urdf differential-drive.urdf"
echo "   check_urdf robot-arm-3dof.urdf"
echo ""
echo "Expected Output:"
echo "- No XML syntax errors"
echo "- Valid URDF structure with proper links, joints, and properties"
echo "- Robot model displays correctly in visualization tools"
echo "- Proper kinematic chain for the robot arm"
echo ""
echo "These examples demonstrate different types of robot models: wheeled mobile robot and articulated manipulator."