#!/bin/bash

# Validation script for Chapter 4 Gazebo code examples
# This script provides instructions for validating the Gazebo examples

echo "Chapter 4 Gazebo Code Examples Validation"
echo "========================================="
echo ""
echo "To validate the Chapter 4 Gazebo examples, follow these steps:"
echo ""
echo "1. Ensure Gazebo and ROS 2 are installed:"
echo "   - Check with: 'gazebo --version'"
echo "   - Check with: 'ros2 --version'"
echo ""
echo "2. For World File Validation:"
echo "   cd docs/chapter-4/code-examples"
echo "   gz sdf -k simple_room.world"
echo "   # This should report 'Valid.' if the SDF is correct"
echo ""
echo "3. For URDF Validation:"
echo "   cd docs/chapter-4/code-examples"
echo "   xmllint --noout robot_with_sensors.urdf"
echo "   # This should report no XML syntax errors"
echo ""
echo "4. Launch the simulation (if Gazebo is available):"
echo "   # Make sure you have a proper ROS 2 workspace set up with Gazebo plugins"
echo "   cd docs/chapter-4/code-examples"
echo "   source /opt/ros/humble/setup.bash"
echo "   # Launch Gazebo with the world"
echo "   gazebo --verbose simple_room.world"
echo ""
echo "5. In another terminal, spawn the robot:"
echo "   source /opt/ros/humble/setup.bash"
echo "   ros2 run gazebo_ros spawn_entity.py -entity robot1 -file robot_with_sensors.urdf -x 0 -y 0 -z 0.1"
echo ""
echo "Expected Output:"
echo "- World file loads without errors in Gazebo"
echo "- Robot model spawns correctly in the environment"
echo "- Sensors (camera and LIDAR) are properly configured and publishing data"
echo "- Robot responds to control commands (if differential drive is implemented)"
echo ""
echo "Note: Full validation requires a complete ROS 2/Gazebo installation with appropriate plugins."