#!/bin/bash

# Validation script for Chapter 2 ROS 2 code examples
# This script provides instructions for validating the code examples

echo "Chapter 2 Code Examples Validation"
echo "=================================="
echo ""
echo "To validate the Chapter 2 code examples, follow these steps:"
echo ""
echo "1. Ensure ROS 2 is installed (e.g., Humble Hawksbill):"
echo "   - Check with: 'ros2 --version'"
echo ""
echo "2. For Publisher/Subscriber examples:"
echo "   - Open two terminal windows"
echo ""
echo "   - In Terminal 1, run the publisher:"
echo "     cd docs/chapter-2/code-examples"
echo "     source /opt/ros/humble/setup.bash"
echo "     python3 simple-publisher.py"
echo ""
echo "   - In Terminal 2, run the subscriber:"
echo "     cd docs/chapter-2/code-examples"
echo "     source /opt/ros/humble/setup.bash"
echo "     python3 simple-subscriber.py"
echo ""
echo "   - You should see the publisher sending messages and the subscriber receiving them"
echo ""
echo "3. For Service examples:"
echo "   - Open two terminal windows"
echo ""
echo "   - In Terminal 1, run the service server:"
echo "     cd docs/chapter-2/code-examples"
echo "     source /opt/ros/humble/setup.bash"
echo "     python3 service-server.py"
echo ""
echo "   - In Terminal 2, run the service client:"
echo "     cd docs/chapter-2/code-examples"
echo "     source /opt/ros/humble/setup.bash"
echo "     python3 service-client.py 5 3"
echo ""
echo "   - You should see the service server respond to requests from the client"
echo ""
echo "4. For URDF validation:"
echo "   - Check the URDF syntax with:"
echo "     cd docs/chapter-2/code-examples"
echo "     xmllint --noout simple-robot.urdf"
echo ""
echo "Expected Output:"
echo "- Publisher/Subscriber: Publisher logs 'Publishing' messages, subscriber logs 'I heard' messages"
echo "- Service: Server logs the request and returns the sum, client displays the result"
echo "- URDF: No XML syntax errors"
echo ""
echo "These examples demonstrate the core concepts of ROS 2: nodes, topics, services, and robot description."